### PR TITLE
Feature/cleanup sbt

### PR DESCRIPTION
**Pull request by jschaul**
essentially just rearranging the sbt file to be a little more consistent with our other sbt files.

### CODE REVIEW

**Comment by jschaul** [comment]
obsolete, since this project, and the `yetu` organization in general has been dead for a few years.

**Comment by larsblumberg** [comment]
@jschaul nice try anyway. Hope you're good!

**Comment by larsblumberg** [comment]
PS: we make good experience with auth0.com as an SaaS auth provider.

**Comment by ghophp** [comment]
👍 hugs guys

**Pull request closed without merging**
