### PR TITLE
Remove old registration flow

### PR DESCRIPTION
**Pull request by ghophp**
remove the registration old routes, and also removed the tests for that particular registration flow.. as the tests for the new flow are already done, nothing to do in matter of tests..

### CODE REVIEW

**Comment by larsblumberg** [comment]
LGTM

**Comment by DaQuirm** [comment]
LA(awesome)TM, it's always good to get rid of the cruft :cat:

**Comment by ElliDy** [comment]
I understood by removing not changing the controller method but removing the routes (so that e.g. "/signup" is not reachable anymore. Can you explain why you did it that way?

**Comment by ElliDy** [comment]
And please also do not remove pages as we may use them after NPower again.

**Comment by ghophp** [comment]
I will remake the PR with just the comment of the routes.. sorry about that..

**Comment by ElliDy** [comment]
No problem. Probably I should have explained it to you more yesterday...so it was more my fault ;)

**Comment by ghophp** [comment]
you can follow: https://github.com/yetu/oauth2-provider/pull/23 this has just the commented version.. I will let this branch on my local machine.. the day that we maybe throw out this old process, we can reuse this PR..

**Pull request closed without merging**
